appSettings:
    AppSettings:
        AppBaseURL: ENC[AES256_GCM,data:052zsYwVR6fvl/ryRP7O60jBCMYYWQ==,iv:wIvuBzzd4eOhizjZZsrzhB8Cq1ZCsHg91kw2sb7bRVU=,tag:TdS7wCTTe9W89VNzw+u1eQ==,type:str]
        AllowedHosts: ENC[AES256_GCM,data:8w==,iv:ptqoZh7uLhPsDTsfVLC/nWuGYBBOCd10RMqEkNERNWI=,tag:sra/JJDBtAeHh55izsk6ug==,type:str]
        AllowedOrigins: ENC[AES256_GCM,data:zNl1Do06+Dk2WIJS136krZPuixcAivHQPi6VuJfSPsi1mcCFmV3VdSw5Qhnj7vZu8iGBpP5RvTKUSzmVo/pVXKIW,iv:O86jtvaUFo0D0lI+otI93t9GullMq12pzuXIFrPu2ug=,tag:2Sg3vvlBKHtljGtQnoCSbg==,type:str]
        SSISchemaFullNameYoID: ENC[AES256_GCM,data:gfN4e6jiGxuo6t3l,iv:HLE+b74Tpkb5tb67jb0W5ty7pdmBCrPFP0+I0QG7nX0=,tag:K35Ns5/tBAqc5lUIxEKUew==,type:str]
    AWSS3:
        Buckets:
            Public:
                AccessKey: ENC[AES256_GCM,data:KZ6ZM5LkVJ7kaLJjz85LJkhjsCA=,iv:t76P7ccWYNJMezryydjHIMpN7f/xj2Y1ppCbcP0iunk=,tag:YXXeKamLP4/O9Bo9p17zzQ==,type:str]
                SecretKey: ENC[AES256_GCM,data:frFcBq+z59pXWhRwy7SrTZTsazUr69iFErx511IUsm1oD5tiZA7hbQ==,iv:aZRRatLfOHSVY1abhfYwdS8VWDIKbzY9XEcECTG0CFg=,tag:FJjQK7JnnVMEXbzBW0a8mw==,type:str]
                BucketName: ENC[AES256_GCM,data:Twxlx1zpnJsIB2BuCnWGQBJr6ALKRw==,iv:T7zjczT98pf9hflU2zhwNPbBitp1Wb3KTfoPoZ4/Rv8=,tag:L/SYTWrjk1CCcRnGZcki8Q==,type:str]
            Private:
                AccessKey: ENC[AES256_GCM,data:4IYHyYVHLMQrJ1eq21x1XNBE3hw=,iv:hjaaorI+tI5HVIOM21D1hR/lHD7NFwzYecaIClGtFUA=,tag:wO3TDiWbsHLvRpVQC5RsuQ==,type:str]
                SecretKey: ENC[AES256_GCM,data:D/my0arhx7RlT6ZeryjQ8PKpj1MScZl0dEDjhyYNhtqh3o5AujDxqg==,iv:G3o5faR1KoQppeyIk2up4OwLSYg7X88InxWeXQ2mxmQ=,tag:Cq28BCxOpuMAcQ3IZBJ5wA==,type:str]
                BucketName: ENC[AES256_GCM,data:O8LgO4mQKBTct/QrWq+RnFhn0vZhI/A=,iv:17fWIKpDHOgo3sCr6DyN1AVZEX62UKnmPYzkbDUlFvA=,tag:mwTx5bIoa9vIZ203WPfiwA==,type:str]
    ConnectionStrings:
        SQLConnection: ENC[AES256_GCM,data:9mdA2SyxV8vwHpPAisJDhZXR2Zdy2OMoQVguoCU4D/hRrEvd4TOMipCtJg8j+5nEBN/tFaeHfoEbMXRTk1bk7WeER/jFimL3h0qs0vA/hoGg+WVnNnSwP9KCGk4yTgcyhsnTp3UU+dolzy9Yw4+0sGcNNBT0KPx5+pxWyIejbzn1aHvDZQiLK30dAkZuszodWWHl7f84bA==,iv:9N8el7FDrL4x2jveBb2+1dybEPGb10pQFeEWQ75ylMY=,tag:2QevzHauSZILs24oGOe/5A==,type:str]
    Keycloak:
        AuthServerUrl: ENC[AES256_GCM,data:HkpmLfgJapUZAh8XPe7qfPrDlevJolj3xkCt,iv:Ryg6L7w5zP6cDoHU7049nFm0M5wxImr+Q7VHGjkcQo4=,tag:07o6KC9XfhouO0fPHldfgQ==,type:str]
        Credentials:
            Secret: ENC[AES256_GCM,data:Mgv3n+S2UEwKxr6dh7K/nOxNbRaJw9VoG/VRQITc,iv:6bYvUp7vr7b6g8+XHELkzJ90gwQjXJwQxvzCr7Xl4WA=,tag:6WN3EUG2HLSxpF2sY5DC5g==,type:str]
        Realm: ENC[AES256_GCM,data:yA60iA==,iv:ZSgs+EHXUPVwoBWtR7p/MnSwbkcKVkKAyIUpBWlIs7Y=,tag:xLYmkNah3T5DOQ2GzGNNIw==,type:str]
        Resource: ENC[AES256_GCM,data:pYiPtt4142s=,iv:/oyphCwy9h2jq5oyIkUXjfM/IVpHnMk25R7HyIRi12Y=,tag:J7MURsVCox87xlI0LSY12A==,type:str]
    Sentry:
        Dsn: ENC[AES256_GCM,data:oKRAAllUFxStFOrS+tRJegJSfUvjw++418Uj9Q+exv8mNOMYohriji+H5Mu4H+7x4a7L6/bApycRKB8lKQNYq3lB6NLaRZ0yKqdRwY4V2gIQCg==,iv:m+03KiMnotT7qzQOi+VhVF2IWKrpBLw6A2pKs77DkGw=,tag:G6bYggL8i8uzzpza6iFJNw==,type:str]
    Emsi:
        ClientId: ENC[AES256_GCM,data:CPbnzXix,iv:FOqF49H2CjjyZCA77AKU1EJar59gzp1KPCmBVsLA4N0=,tag:eCpZ5lrskOX/mL0MLaOCxQ==,type:str]
        ClientSecret: ENC[AES256_GCM,data:W7gvATo8t1Q=,iv:mLRgSIqLwvD3VJA90zWj0Ct99u5oXXC6L1tB2PfBiXI=,tag:xAmujHrH0ZxJH4f3gpOdOg==,type:str]
    SendGrid:
        ApiKey: ENC[AES256_GCM,data:Cq0R6UIXjeOxGKd3mFZljJt7ucNXlac6pogy6YmHY7gH/kEEamIeLcCCQvygnxyfHebGaG+3gQlFMloSPTeuMVv0HaLM,iv:nA0qaXDKR01rqF7FKXirTCXUHvFLnGGoJj9Jeb8bvKg=,tag:lf6RQj9q7O85ODcHilPttg==,type:str]
    Zlto:
        Username: ENC[AES256_GCM,data:O+Fi2tSOkaHuLTvhdg==,iv:/5TmT2Yfiaf22VvbWt6sRvchT7Ncpzrxe4T9TnbQJHg=,tag:hvsJJ6IeuVI5EENKOlMpcw==,type:str]
        Password: ENC[AES256_GCM,data:v7oRpYwPwjzd,iv:ReY5Ma9bMDarSQrKoAwi/GbLPEHOMwamKgVpDYASxcg=,tag:z/BdHF0vVa6urigYbX+UvQ==,type:str]
    AriesCloudAPI:
        BaseUri: ENC[AES256_GCM,data:txQniDbD7J0dMq8bX2LUoye/EXn4fP5KtzJAR8LLIvOCbw==,iv:HKXVSeoDYFx/Ukg+c6lJpmtkuJzaWdIbsun+vHFVnHo=,tag:0T3xTtUbsSQYdgJlUbHN8A==,type:str]
        DebugOutput: ENC[AES256_GCM,data:Wr25RDE=,iv:3UNzWP3LbDCqJ2cKSM0P8xhJ9qv9CpdHBBd5G760ELs=,tag:l9XYS4mc7IjuEfER6l6SpQ==,type:bool]
        GovernanceAdmin:
            ClientId: ENC[AES256_GCM,data:bnLU+X+tzmx13Q==,iv:/5YRf7Mnu/WelVAtzuwvnvPPjyf97/UMWWE4oa45JTU=,tag:Xapmau9kZv/n5+9CDdjq4w==,type:str]
            ClientSecret: ENC[AES256_GCM,data:rNeIyFR/tIGK0H+VSnz665lL2eZUAnVW/G9+6zq5wjQ=,iv:p1N8T8PCwgPFF94gLGIDCl8/8jj8so+MN8wC0O0XkOE=,tag:VXE3Qm8x5HkI9XB7FZb9CQ==,type:str]
        OrganizationId: ENC[AES256_GCM,data:hO14nq7IKxe0pBt7Ub2QrkOQZ3juRnvUVeyG5rp3LdomJWj9,iv:jR+EP3aC5VIV4xfIpwolCS0s0zipPf4D0CENvqHKg/8=,tag:xYCgXyt1eU9Nw+L+djf3AQ==,type:str]
        TenantAdmin:
            ClientId: ENC[AES256_GCM,data:sN6ic/XTGzk=,iv:yfHzzJqpzRNaxn6x7kXfOzBwTsBVxLk8gF/Xyy5YaWM=,tag:oNFe0iIVFdBaCbTEimT7eA==,type:str]
            ClientSecret: ENC[AES256_GCM,data:IJmsDFJvvQWUyJPosV7/SyyiIKCq8NT+1wpxF9/MkLI=,iv:GbDHpQaVqLm8WaOXzyVKZmMRj77WZqAhrkuaYC2JkdM=,tag:9Xg28d7njLc6VQyVs5yILA==,type:str]
        TenantTokenCacheRotationIntervalDays: ENC[AES256_GCM,data:bA==,iv:eBtK1P3uMGacLzoRGJEofMsjRH+DVsUWwIHs+isEA+g=,tag:T47rEoDuPqE5wJVICxwbvA==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:210913241065:alias/helm/yoma-dev
          created_at: "2023-09-18T12:43:26Z"
          enc: AQICAHiIBZY/vSCV0N0rJ1zU5SgMLl7KVz/655pZ90kE4uwaNwGDC3EwSg6skDuyETp/AVVqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM59JE9ckC6/q58ZA9AgEQgDsvEM10JhPmz9S7yeMijYwZuqUVQjE1x+GWhw2qBf3I0jA3nxPHB0sutIOIm67Fd3uROQ+Jfy/CNPCdRQ==
          aws_profile: yoma-sso-dev
        - arn: arn:aws:kms:eu-west-1:210913241065:alias/helm/yoma-dev
          created_at: "2023-09-18T12:43:26Z"
          enc: AQICAHiIBZY/vSCV0N0rJ1zU5SgMLl7KVz/655pZ90kE4uwaNwGDC3EwSg6skDuyETp/AVVqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM59JE9ckC6/q58ZA9AgEQgDsvEM10JhPmz9S7yeMijYwZuqUVQjE1x+GWhw2qBf3I0jA3nxPHB0sutIOIm67Fd3uROQ+Jfy/CNPCdRQ==
          aws_profile: ""
    lastmodified: "2025-11-20T10:21:19Z"
    mac: ENC[AES256_GCM,data:NESdkWWzoJqvEmtwFLfftL5wStTb5LO9T21vvzROq+gXbMFlsv/8947R/Y3A5wJJzAUJeQu9e7r3qERNP04InTHUuu80+WCyo57zz08DKBpMDVo4cZ0pco72JhV/v7abbAbqBbR9E53Cyz4cAQNJTTLOg408sd6nEV/68sD+wWo=,iv:0KiqfphasM6Y5cOiAIs2Y5BEkG/P/4+mxIgSEf0aCAw=,tag:73omJ+9OlkC6iZ2oBldG+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
